### PR TITLE
Added VariableAsignmentExpression and VariableReferenceExpression

### PR DESCRIPTION
**Pull request by lucaswoj**

### CODE REVIEW

**Comment by lucaswoj** [comment]
(Gonna go easy on unit tests. We need a final demo. As soon as this bites us in the ass, we'll go back and add unit tests)

**Comment by mtrberzi** [comment]
Works for me, let's get this through and move on. We need a final demo.

**Comment by lucaswoj** [comment]
:ship:?

**Comment by mtrberzi** [comment]
:ship:

**Pull request merged**
