### PR TITLE
Added checkstyle

### PR DESCRIPTION
**Pull request by lucaswoj**
Before every commit, do some static analysis on the code to enforce coding style. Rules have largely been adapted from Google's checkstyle settings.

95% of changes in this PR are
- Making properties `final` where possible
- Using diamond type inference where possible
- Adding `@override` annotations where appropriate
- Fixing line lengths
- Fixing whitespace formatting inconsistencies

### CODE REVIEW

**Comment by mtrberzi** [comment]
Strangely enough, your build has failed... maybe this is still a residual refactoring issue. Fix test cases and push again.

**Comment by lucaswoj** [comment]
Looks like just a Java version inconsistency. All better.

**Comment by mtrberzi** [comment]
So, how does this work? Does the PR automatically get checked and then errors come back to the developer? I don't actually see any feedback here (although maybe that's because nothing has technically been enabled yet).

**Comment by mtrberzi** [comment]
Ah, okay, so it's a Gradle plugin -- then do we need to remember to run `gradle checkstyle` or is that now an automatic job on ANY run?

**Comment by lucaswoj** [comment]
`checkstyle` is run along `check` which is the preferred way of testing a build. Travis CI will run this automatically. Your IDE will show violations inline.

**Comment by mtrberzi** [comment]
Cool. Let me pull this branch and check the checks...

**Comment by mtrberzi** [comment]
Nice. :shipit:

**Pull request merged**
