### PR TITLE
refactor: rename "endpoint" to "port"

### PR DESCRIPTION
**Pull request by mtrberzi**
A quick fix for #72.

### CODE REVIEW

**Comment by maxqchen** [comment]
This is just a mass rename right? If it still builds & tests fine then I don't see anything stopping the merge.

**Comment by mtrberzi** [comment]
Fair enough. I just wanted another set of eyes to make sure I didn't miss anything obvious.

**Comment by mtrberzi** [comment]
I did miss several, do not merge.

**Comment by mtrberzi** [comment]
Okay, have a look now -- I think I got them all.

**Pull request merged**
