### PR TITLE
Refactored codebase to share values between front end and back end

### PR DESCRIPTION
**Pull request by lucaswoj**
This is a high level reorganization of our codebase to allow us to share primitive values between frontend and intermediate representations.

The most elegant approach to elaboration is to make the intermediate representation an exact subset of the front end representation. This avoids having to write a translation step where we turn a frontend boolean into an intermediate boolean, for example.

Specifically, everything lives in `org.manifold.compiler`, frontend only things live in `org.manifold.compiler.front` and intermediate only things live in `org.manifold.back`.

### CODE REVIEW

**Comment by lucaswoj** [comment]
I pinky swear that no logic was changed here, just organization of code (and I removed a checkstyle rule that complained about the order of inputs -- that's too pedantic for me)

**Comment by lucaswoj** [comment]
Perchance we should change the namespace to `io.manifold` instead of `org.manifold` while we're breaking shit

**Comment by mtrberzi** [comment]
Are you sure? We never got the domain "manifold.io" and apparently that's
taken by some web app called "Hover" (don't ask). We're still
manifold-lang.org as of now...

**Comment by lucaswoj** [comment]
Oh! Right. We should change it to `org.manifold-lang`, then :-)

**Comment by lucaswoj** [comment]
I should re-rename `org.manifold.compiler.back` to `org.manifold.compiler.middle`

**Comment by lucaswoj** [comment]
Subsumed by #126

**Pull request closed without merging**
