### PR TITLE
Switch primitive types to be singletons

### PR DESCRIPTION
**Pull request by TysonAndre**
Ensure that exactly one of each primitive type can exist.

For #82

### CODE REVIEW

**Comment by lucaswoj** [comment]
Brilliant work Tyson! You can merge this as is :smile:

**Comment by lucaswoj** [comment]
Fixes #82

**Comment by mtrberzi** [comment]
Good work, merge when you are ready!

**Comment by TysonAndre** [comment]
oops. Edited, but commit message in git might still be wrong.

**Pull request merged**
